name: chess_server
description: A tcp server for my chess game
# version: 1.0.0
# homepage: https://www.example.com
# author: martial <martial.garchery@gmail.com>

environment:

dependencies:

dev_dependencies:
  pedantic: ^1.8.0